### ISSUE TITLE
Just not working at all.  Lost several auctions so far. 

### ISSUE THREAD

**Issue by brianm80** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#31]
Hello.  This looks to be a pretty genius idea, but it's just not working for me.  I'm wondering what I'm doing wrong.  I've done a few tests here and lost every one of the auction snipes I've set up.  There are no options to select.  It's as if the bids just aren't being sent to the site at all.  They are stuck in limbo in my "My Snipes" section, and they say "Waiting...." forever even after those auctions are complete and someone else won.  Does this make sense?  Is there some other setting I need to apply to get the bids to actually to through at the last second?  It seems that's the issue...the bids are never being sent, yet they look like they are set to go for each item I have set up for bidding.  They show wanting to send even on auctions that I have lost.  

I'd love to keep using this system and tell my friends about it, but it's caused me to actually LOSE auctions I may have won otherwise, so I can't quite do that yet.  

Thanks.

**Comment by brianm80** [comment]
I can see now that I'm able to look at "closed" issues on here and a few others have had the same issue as me.  I see the only recommended solution was to download the latest version (as recently as a week ago).  I haven't seen anyone say that fixed their issue though. 

I downloaded this last night for the first time, on 8/22/24 at around 9 or 10pm EST.  So I have what I assume is the absolute latest version.  

I paid for unlimited 1 month, to give this whole thing a try.  So far it's been a bummer.  Hoping to get some kind of fix and figure this out, because this can be an amazing tool!

Any ideas what's going on?  Why aren't the bids even being sent at all, either too early or late for auction end time?  

Thanks!

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Brian,

It sounds like it may be a time discrepancy issue as it usually is, the time on your computer has to be precisely right or you must at least be connected to the internet when the app starts so it can get the latest time... have said that are you behind a proxy also what time zone are you in?

**Comment by brianm80** [comment]
Thanks. 

I'm in Eastern, or EST.   Computer is set correctly to Windows' own time clock or whatever.  I'm definitely always connected to the internet on the laptop I use.  So the app actually uses the precise time of what the computer thinks is the current time....that makes sense.  But my time is correct on the computer.   And if it was just a time zone issue (like off by 3 hours, or I was "ahead by 3 hours" or something), the waiting auctions wouldn't be forever showing that they're waiting to bid, would they?  They'd eventually show that I lost those auctions once I caught up to whatever time the goodwill site is in.  

No, not behind any sort of proxy that I know of.  I don't think I'd even know how to set that up.  

Is there some way to manipulate the time in the app?   Is there also a way to set the snipe timing from whatever it is to a different delay?  Like is it set to 2 seconds but I should have it set to 4 seconds before the auction end, or vice versa?  Not that this is even the issue, that's kind of just a future tweaking question for as I'm learning how it all works.  


Thanks!

**Comment by brianm80** [comment]
Wish I could show a screen grab of the My Snipes section, but I accidentally cleared out all the old ones when playing around with the options under "Menu".  I chose a few different things for Expire Stale to see what it was.  Obviously that deleted anything that already ended.  So that tells me the app is recognizing standard time regardless of the time zone I or the auction site is in.  Weird.

**Comment by brianm80** [comment]
Ok, this is really weird now....just playing around with a few more testing theories and this "buy license" screen just popped up!  I paid for the one month unlimited through Venmo (I think, or Cashapp?) last night when I signed up.  Would this screen popping up mean that somehow I am not really authorized to do any sniping and my payment didn't truly get applied to your system?  That might make sense and be the root of the issue!

![image](https://github.com/user-attachments/assets/1c5f807e-5b4f-45e6-9e4e-8eaec01e8cd7)

**Comment by brianm80** [comment]
Holy shit dude, I think that was it.  I'm kinda tired and can't think of anything to buy super cheap to try a snipe right now, ha ha.  I'd love to try this out now but I'm drawing a blank.  I have a real potential item set up for tomorrow morning though.  

I just went into my Venmo account to look at the history, and the payment last night somehow isn't even showing.  Even though it said the bid sniper app was activated successfully last night right after I did the payment!  

I just processed the payment (again or for the first time now??) and it said activated successfully, again just now.  I typed a dummy number for an auction and it said syntax error since no such auction existed, but that was better than taking me to the Bid Sniper License page as it did a couple times just minutes ago.  So that looks like it means I'm now a paying member?  And I wasn't before, up until now?  Would that be why the snipes I had set up were just sitting there waiting to send through but never did send?  Strange that I'd be allowed to create future snipes without being forced to pay.  

Hopefully this was the issue.  Not sure why I could generate planned snipes before, but I'll see if my next one tomorrow morning goes through!  

Can you see if I'm now a paying member, and you show that I actually somehow WAS NOT a paying member up until about 10 mins ago??

**Comment by brianm80** [comment]
Damn.  That wasn't it at all.  Still didn't send the snipe this morning.

**Comment by shopgoodwill-auction-sniper** [comment]
Can you confirm if the date time on your auctions correlates to the end date time displayed on the sgw site?

**Comment by brianm80** [comment]
Yes, those match.  I'm out of ideas!

**Comment by shopgoodwill-auction-sniper** [comment]
Oh ok do you hear the snipe shoot sound at all or even the snipe load sound? What sounds do you hear ? 👂

**Comment by brianm80** [comment]
Not at home just yet.  I'll check when I get back.  I actually turned the audio off since it was bringing up windows media player every time and got annoying, ha ha!  I'll try again with the sounds. I think some sort of cha ching would play when I would create a snipe.  Never heard any sounds happening during the seconds of an auction ending.  So that tells me it's just not sending the snipes.

Still wondering about payment stuff through venmo. Even though both times I did the payment and got the activation confirmation I am not seeing the $9.99 charge yet as a line item in venmo!  Weird.  Do you see my account as having paid on your end?

**Comment by shopgoodwill-auction-sniper** [comment]
Windows media player? It's not suppose to do that. I thought you said you were on Mac?

**Comment by shopgoodwill-auction-sniper** [comment]
No we don't show any licenses for you and never received a payment from you either.

**Comment by brianm80** [comment]
Ha. No, definitely windows. 

Yeah, the mp3 or wav file will bring up that default player associated software and I have files set for repeat so it would just cha ching on a loop every 3 seconds.  It was funny but got annoying.

**Comment by brianm80** [comment]
Well, there you go!  Is it in fact the payment processing problem that is causing us to be chasing our tails here for hours trying to figure this out?  How else can I pay, if that's the issue?  I did it twice and the activation confirmation popped up both times.  But like I said, I'm not showing it in venmo for either time.

**Comment by shopgoodwill-auction-sniper** [comment]
If it's not asking you to pay then you probably paid already.

**Comment by brianm80** [comment]
Ok. So what else can we do at this point?

**Comment by shopgoodwill-auction-sniper** [comment]
We develop on Mac here so we will need to get a windows to fix it...

**Comment by shopgoodwill-auction-sniper** [comment]
So just to isolate the issue, even when the auction end date time passes by it still just says status waiting? it never changed to other statuses?

**Comment by brianm80** [comment]
Yes.  Correct.  That's what it was doing.  It was saying "Waiting" forever, even after that auction ended. 

Today, just now when I looked, it says "Failed!".  So what is the difference for those status reports?  

I said above Windows, so not sure how we started talking about Macs. 

When you said you need to "get a Windows to fix it", did you mean a Windows developer?  Windows customer service person?  Or did you actually mean a Windows version of this software?  (as in, it only works for Mac)?  

What about the payment issue?  That seems to be an issue, correct?

**Comment by shopgoodwill-auction-sniper** [comment]
So far we have documented that you reported 2 issues, one with the sound, which we have fixed now, you can download the new version by running the command on our homepage again to update at Snipeable.com and two the snipe is failing on Windows because we have extensively tested it on Mac but we don't have any Windows systems here to extensively test it on Windows, we have tested on Windows Virtual Machines but that doesn't always reveal the issues so we are looking into that next, we should have it fixed for you very soon, but our only delimiting factor is we don't have any native Windows here.

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by brianm80** [comment]
Thanks Ahmed,
It took me to an expired link at Mediafire.  
So does the team still think I have an issue?  I haven't had an auction to try in the past 2 days, but I'll try to find something to try out a snipe tonight on something small.  
Are all my issues fixed?  What were you referring to below?

Thanks,
Brian
    On Monday, August 26, 2024 at 03:09:53 PM EDT, MasoodAhmed ***@***.***> wrote:  
 
 


to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by brianm80** [comment]
OK.  Just tried a cheap auction with a snipe.  It didn't go through and I lost the auction.  ;

It's still stuck in a permanent "Waiting" in orange font.  

Installing the new update to the app did not fix any issues.

**Comment by brianm80** [comment]
Should we reopen instead of marking this as closed?

**Comment by shopgoodwill-auction-sniper** [comment]
Brian that's crazy that you didn't reply to our update but you responded to some random spammers message to you to download some arbitrary file from mediafire? Obviously that user is not the admin account so I don't know why your brain would just trust to download some random file for media fire when you already know the only to download and install our app is from our homepage at Snipeable.com ... I didn't think I would have to explain common sense to you but obviously that message was not from us and that user is not the admin for this account nor is that mediafire link anywhere on our website so why you are responding to a random spam message that no longer even exists because it was automatically detected and flagged by mediafire and GitHub as a malicious link and you are here asking the random spam user for the update and help?

**Comment by shopgoodwill-auction-sniper** [comment]
furthermore we have deleted your repost of that spam users mediafire link why would you repost that spammers message again on this discussion even though you see his original message was already flagged and removed? We are very close to refusing service to you  and completely blocking your user account if you continue to post dumb things!

**Comment by brianm80** [comment]
How did you give some random spammer my email address?  The link was not harmful, it was just spam.  Nothing was downloaded from there.  How did you let that happen, though?

Anyway, now that we're past all of that with the many sentences typed above, we still don't have the fix.  Yesterday your team reported the issue was finally fixed, and that the issue was closed.  It didn't get fixed though.  Still a failed snipe as I typed above.  That's the main issue here.  The spammer thing is a separate concern.

**Comment by brianm80** [comment]
I didn't post anything to do with any spammer.  I hit reply.  Perhaps your system did.

**Comment by brianm80** [comment]
Wow!!!!  Who posted dumb things?  The issue still hasn't been fixed.  That's all I have posted.  I have no idea what is going on and why someone got so hostile here.  Who is working on the fix?

**Comment by shopgoodwill-auction-sniper** [comment]
If you repost that random spammers malicious link again we will block your account completely! Don't act stupid again or we will refuse service to you!!! That is your one and only warning, we helped you already and you didn't respond but you respond to some spammers message, if you do one more stupid thing you will be out of here!!!

**Comment by shopgoodwill-auction-sniper** [comment]
Ok if the issue hasn't been fixed you should have said something not stood there quiet like a dumb ass and then you all of sudden reply to a spammers message, dont argue with me because I am 2 seconds from blocking you from wasting our time, just listen to me and don't act stupid or again or we will throw you out of here faster than you can say why?!!!

**Comment by shopgoodwill-auction-sniper** [comment]
Use your brain and you will understand why we are telling not to post BS here and waste our time!!! Don't argue with me that is not what we are here for we are here to help you and we can't do that if you're acting that way.

**Comment by shopgoodwill-auction-sniper** [comment]
Use your brain and you will understand why we are telling not to post BS here and waste our time!!! Don't argue with me again, that is not what we are here for, for you to waste our time arguing common sense to you, we are here to help you and we can't do that if you're acting that way.

**Comment by brianm80** [comment]
I haven't argued, I haven't posted anything malicious....apparently somehow some spammer got involved and posted something on our thread and it irritated you?  I really don't know what's going on with that at all.  Github is new to me as of 3 nights ago when I bought the software and it didn't work for me.    

Anyway, I was simply asking why we said there was a fix for Windows but I reinstalled the latest version as you mentioned last night and it still didn't fix the issue.  Were some changes to the code made, or does it seem that I am still running the same software I was running before making the change a half hour ago?

**Comment by shopgoodwill-auction-sniper** [comment]
No you did report the spammers link by replying to his malicious email that githubs system already flagged and removed but still emailed to you, obviously we would never ask you to go and download some random file from somewhere other than our website, so if the message was already flagged and removed and is no longer even here then why would you reply to it only reposting the malicious link? Don't do it again, if you do It again you're banned permanently. Also don't waste our time arguing common sense to you that is not what we are here for for you to waste our time arguing common sense to you!

**Comment by brianm80** [comment]
Oh I see now, you think I was only reply to a spammer and not to you!!!  No, that's not what happened.  I have been busy all day since you closed the issue last night, and JUST NOW had a chance to dig into this again.  I hit reply to the latest comment on the thread.   It's really that simple.  I just couldn't get back into this until this evening.

**Comment by shopgoodwill-auction-sniper** [comment]
Yes correct, a spammer posted a malicious link on here and it was obviously a spammer and malicious link because it wasn't from us or our website so why you would all of sudden reply to their message but no reply to our actual help we gave you is mind boggling??!!! And then you wanted to argue about very bad move, using our software is a privilege and we can take it away from anyone we think is abusing our service FYI.

**Comment by shopgoodwill-auction-sniper** [comment]
Ok no problem, there is no damage done because all the malicious links were removed but please do not repost that spammers malicious link again, and also only talk to us if you want us to fix your issue, obviously don't just randomly start talking to some other spammer on the thread. Thank you!

**Comment by brianm80** [comment]
I assumed it was one of you guys.  I really had no idea.

**Comment by shopgoodwill-auction-sniper** [comment]
If the message doesn't come from our account then obviously it is a malicious spammer, so please pay attention as these kind of things are serious. Thank you!

**Comment by brianm80** [comment]
I only want a fix to the issue.  I do not want to talk with spammers.  Nothing else matters here to me.  Just the fix.

**Comment by brianm80** [comment]
I assumed that WAS one of your accounts.  I assumed this is all happening overseas, and not here in the US.  I thought that was one of your team.

**Comment by shopgoodwill-auction-sniper** [comment]
That's ok, you didn't know, but now you do so it's ok we can move on from here but please don't waste our time arguing either it just makes it harder for us to help you, so we will help you fix the issue as we have been but you have to pay attention and reply promptly otherwise we will think you are just wasting our technical support we are giving you. Thank you for your understanding, we appreciate you but please understand we have no time to waste here, our time is precious and expensive here and we are giving that to you for free at this point so please appreciate it and pay attention and we can fix your issue in no time and very smoothly but only if you let it. Thank you!

**Comment by brianm80** [comment]
I am definitely paying attention.  I am ready for the fix!  

I tried the new software (downloaded from the site within the last hour).  It didn't fix anything and the waiting snipes are still stuck in limbo forever unless I clear them out.  

I'm out of ideas.  Do other people have success with it on Windows, or only on Macs?

**Comment by shopgoodwill-auction-sniper** [comment]
So please follow my original instructions and only update/install by running the command on our homepage and don't get distracted by spammers, pay very close attention those kind of details on the internet because downloading random malicious files is serious, it could have done big damage to your computer FYI so obviously we don't want that for our users. So please update/install the latest version by running the command on our homepage at Snipeable.com and if there is still something that is not working please just tell us and we will quickly fix it for you as we have been we would never ask you to download some random file from mediafire.

**Comment by brianm80** [comment]
I did just that.  I updated/installed the latest version.  

I don't know how to do it by running a command though.  I did it by clicking on the Windows Installer version.  Is there a better way than what I did?  

![image](https://github.com/user-attachments/assets/f1a55f06-8cc1-4abd-a9f4-167a41b2b58c)


Now that I look at this more closely, that installer is not updated within the past 24 hours as I would expect it should be from the description above saying there was a fix.  

So is that not the latest version?  Where else can the latest version be found on Snipeable.com?

**Comment by shopgoodwill-auction-sniper** [comment]
if it is still exactly the same then it probably did not update, please ensure you are running the command correctly on our homepage at Snipeable.com and delete the old desktop shortcut and also delete the Bid Sniper folder In your user profile folder usually located in C:\Users\<Your Username> just to ensure when you reinstall it should re-create that folder for you and the desktop shortcut confirming you have indeed installed the latest version correctly because we made a lot of changes and for you to say none of the fixes are working doesn't sound right...

**Comment by shopgoodwill-auction-sniper** [comment]
no the installer never changes and also you shouldn't download the installer if you should have we would have put that in the homepage instructions but instead we have a simple one line command to copy and paste to install/update so please follow the instructions on our homepage as they are there for a reason.

**Comment by brianm80** [comment]
![image](https://github.com/user-attachments/assets/e921f52b-6dc5-402e-b669-75f335228c1e)
And I believe this is what I copied and pasted into the browser 3 nights ago when I first got the software.

**Comment by shopgoodwill-auction-sniper** [comment]
you should never have to download the vbs installer file, all you need to do to install/update is simply copy and paste one command from our homepage as our instructions say so please follow the instructions as they are there for a reason...

**Comment by brianm80** [comment]
I'll go in and make sure to delete everything related to the software on my computer right now and try again?

**Comment by shopgoodwill-auction-sniper** [comment]
ok 3 nights ago is not the same as today, you obviously still have the old version installed because you did not follow the install/update instructions in our homepage, if you did you would already have the latest version with all our fixes we did for you.

**Comment by shopgoodwill-auction-sniper** [comment]
yes, the installation process, nor our support process is complicated at all, this is a very smooth process, so lets keep it that way by following instructions and paying close attention to the technical support we give you. Thank you!

**Comment by brianm80** [comment]
OK, so which instructions?  The page is pretty full of lots of words and command line looking things all over. 

Here's the problem.  I keep getting told to get the UPDATE, and I would love to get the update.  But apparently I just reinstalled the old version.  And I looked all over the page but do not see anything that specifically says update except for that Invoke Web Request thing that was in my last screenshot.

**Comment by brianm80** [comment]
I'll delete the old files right now first.

**Comment by shopgoodwill-auction-sniper** [comment]
Ok simply open powershell and copy and paste that command it's done we made it that easy!

**Comment by shopgoodwill-auction-sniper** [comment]
Let me ask you a question was the sound effects working in that last version you thought you had installed/updated because if the sounds still didn't work then you didn't have the latest version...

**Comment by brianm80** [comment]
I've never used or really even heard of powershell.  I'm trying it now!

Oh, it's the same thing as I saw 3 nights ago when first installing and an hour ago when I thought I was installing an updated version of the software.  

It looked just like this with all 3 installs/update attempts so far....
![image](https://github.com/user-attachments/assets/df79eda7-eff5-482a-8151-4e4c4d0f458e)

**Comment by brianm80** [comment]
I don't think the sound effects were working.  But I think I turned them off that first night I was learning how to use the software.  I'll check again when this "update" finishes, if this is in fact updating.

**Comment by brianm80** [comment]
![image](https://github.com/user-attachments/assets/1b1c9b1e-3f4f-4be0-859e-2c54d91ff154)

**Comment by brianm80** [comment]
There's the screengrab again, with my directory name blocked out....

**Comment by shopgoodwill-auction-sniper** [comment]
yes, that's correct you are doing it correctly by following the instructions on our homepage.

**Comment by shopgoodwill-auction-sniper** [comment]
when the new version installs the first thing you can see is if the sound works now then you indeed have the new version.

**Comment by brianm80** [comment]
Just tried another auction snipe.  It still didn't work.  It just stays stuck on "Waiting" in orange text.  No sounds, no indication anything happened at the time of the auction end.  Bummer.  I was really hoping the newest patch or update was the fix!!

What else is there left to try to fix this?  Are any other users on Windows having issues or are all the successful customers of this software using Macs?

**Comment by brianm80** [comment]
If I don't reply right away this time it's because I've gone to bed and then often am busy during the day.  I'll try to monitor this system for any responses and update suggestions.

**Comment by shopgoodwill-auction-sniper** [comment]
Oh if it said something could not be uninstalled during installation that means one of the files was in use probably because you may had the program open in your system tray or the file may have been in use by your operating system, just to be clear the installation process should produce no errors at all, if it did then it didn't install correctly so you may have to install it again but only run the installation again after you have confirmed the app is not already running minimized in your system tray and once you are sure it's exited out then restart your computer to ensure no files are being locked by your operating system and then delete the Bid Sniper folder from your user profile and then once you have completely and successfully deleted the Bid Sniper folder from your user profile folder successfully then run the installation on a new reboot and also confirming the app is not running while you are trying to install/update it...

**Comment by brianm80** [comment]
I did make sure I stopped the software first and then uninstalled every trace of it.  Is there some other file location on the hard drive I should be looking for to delete first?

I'll try next with the suggested reboot after uninstalling it yet again.  And being sure it's not minimized to system tray.

**Comment by shopgoodwill-auction-sniper** [comment]
no its only in your user profile folder called Bid Sniper and the desktop shortcut is all the files for the app so if you successfully delete those 2 things then the app is successfully uninstalled but please ensure you reboot after uninstalling too clear any used files by the operating system and then reinstall on a new reboot, the bottomline is you should not see any error during installation at all.

**Comment by brianm80** [comment]
During that second reinstall I did, after being sure the software was not running, I got no errors and it said it was successfully installed.  I feel like it's still installing an old version?  

But that screen grab above shows a 24.25.08 file version, which was yesterday.  So it looks like I got the latest version!  So weird.  

OK, rebooting in a second...

**Comment by brianm80** [comment]
OK, this time it played a sound at startup.  That's a good sign.  It was a really long weird mix of crushing paper and maybe some coins and stuff.  Not exactly what I would expect, like a hammer for an auction or something!  

I'll try to think of something to try it out with now.  I think I can even purposely underbid on an item, with no plan to win, right?  Just to try out the functionality of it.

**Comment by shopgoodwill-auction-sniper** [comment]
That's not the sound of crushing paper and some coins, it is the sound of a sniper rifle loading which is what the app is so the sound means its loaded...

**Comment by shopgoodwill-auction-sniper** [comment]
before you try adding a new auction snipe, please try manually placing a bid on the item on the sgw website to see if sgw website is even accepting your bids, sometimes users accounts have multiple unpaid items and they think its the sniper app not working, its sgw website preventing the bid because they don't allow more than a certain amount of items and certain accounts to only bid only under certain conditions have been met, so please first place bid manually on the sgw site and ensure your account is even good enough to bid on an item, then proceed to setup a snipe shot...

**Comment by shopgoodwill-auction-sniper** [comment]
an auction hammer sound effect would make sense if this was an auction app but its actually an auction sniper app, its like turning your computer into a sniper rifle basically for last second auctions snipes.

**Comment by shopgoodwill-auction-sniper** [comment]
when the snipes fire you should hear a sniper rifle shot sound at the very last second of the auction that means it fired shot...

**Comment by brianm80** [comment]
I did think of that already, yes.  I have been buying stuff directly on the SGW website and bypassing this snipe software.  That works just fine and I've won things there.  I make sure to pay right away.  I was wondering if that was part of the issue when I first tried this software 3 night ago and it wasn't working.  

Oh, so that's like a rifle loading sound maybe?  I'll have to listen to that again.  

By the way, what is the delay or time before auction end that the snipe gets sent?  Is it like 2 seconds?  5 seconds?  I wonder if a slower internet connection could cause a problem!

**Comment by brianm80** [comment]
Aw man.  It still is stuck on "Waiting" even after the auction ended.  I assume it still should send my low bid, even if it wasn't enough to win.   It never sent the snipe.  No rifle shot sound either.

**Comment by shopgoodwill-auction-sniper** [comment]
Whatever the issue is that you are experiencing it seems like we are one change away from fixing it, I personally think there is a date/time issue occurring with the difference in timezone as that is most of the problems we have been having with this new major version, but that is just one fix away and as you can see we can issue an update immediately when we find issue... The auction snipe shot is fired at the very last second of the auction the software itself takes into consideration network delays and slower connections too, of course it works perfectly when we test it but we will fix your issue too.

**Comment by shopgoodwill-auction-sniper** [comment]
Yea in that case based on the behavior you described it sounds like a date/time issue because of the timezone difference can you see if the auction end/datetime displayed in the apps my snipes section correlates to the auction end/datetime displayed on the sgw site but it should display the auction end date time in your timezone not the sgw server timezone, please navigate to an auction page and add the item to your my snipes section and send us a screenshot of you on the actual auction item page that you just added with the my snipes item displaying in the screenshot along with the auction item page in the screenshot as well so we can see if it is calculating your timezone difference properly?

**Comment by brianm80** [comment]
OK.  Makes sense.  I guess I'll just keep waiting patiently for the next update/fix.   This will be an amazing software for me, and I'm sure it's been great for many others already.  I look forward to using it soon and would definitely buy the longer licenses or lifetime membership when I can see that it's working for me.  

The time zone part makes sense, but also raises more questions.

**Comment by brianm80** [comment]
OK, I'll do that now....

**Comment by brianm80** [comment]
![image](https://github.com/user-attachments/assets/5c470ce4-e169-48f9-ab93-87f0c23bf232)

![image](https://github.com/user-attachments/assets/c7ff8dea-c77e-4808-9a1a-9be719bb40c1)

![image](https://github.com/user-attachments/assets/e878546d-101a-4997-b575-72a018a2fe97)


I grabbed the bid history too, which seems to be the only place you can see timing.  Those bid timings are given in Pacific time obviously, and I'm bidding in EST Eastern time, 3 hours ahead.  So those match.  

The listing itself doesn't show anything for time except for "Time left", unfortunately.

**Comment by brianm80** [comment]
What I should do next is look at this same item in My Snipes 3 hours from now, and see exactly what that shows.  Will it change to "Failed!" in red text at that exact moment of 3 hours after that auction ended?

**Comment by brianm80** [comment]
Using this time zone theory I even manually just changed my time zone settings in Windows, to make my now 12:19am EST show 9:19pm Pacific time that the SGW site uses.  

It didn't change the "Waiting" in the My Snipes section to anything else on that auction.  It still just says Waiting.

**Comment by shopgoodwill-auction-sniper** [comment]
Thank you for those screenshots but what is the item id for that auction?

**Comment by brianm80** [comment]
![image](https://github.com/user-attachments/assets/9dea56b5-2aca-4fbb-ba8e-85b14da95d98)

**Comment by brianm80** [comment]
207947443

**Comment by shopgoodwill-auction-sniper** [comment]
perfect thank you for that information brb...

**Comment by shopgoodwill-auction-sniper** [comment]
ok based on the information and screenshots you provided it looks like its calculating the timezone difference correctly, which means its most probably the timer itself, so let me look into this further tomorrow and I will get back to your hopefully with a fix for you...

**Comment by shopgoodwill-auction-sniper** [comment]
oh btw are you using windows 10 or 11?

**Comment by brianm80** [comment]
OK, thanks.  Yes, I'm getting very sleepy, ha ha.   I look forward to whatever suggestions you may have tomorrow.  

Thanks again for the help.  I'm hoping we can push through this!!!

This main computer I use is Windows 10 Pro.  

Do we think there could be some kind of weird firewall setting thing causing all of this?

**Comment by shopgoodwill-auction-sniper** [comment]
Oh I believe I see the issue, it is because you are setting the bid too low lower than the current bid so the snipe is never firing  but we will look into this further tomorrow...

**Comment by shopgoodwill-auction-sniper** [comment]
It could be your firewall too yes, what firewall are you using, so we can look into that further too? If the settings are too aggressive it might be canceling the timer...

**Comment by brianm80** [comment]
OK.  In checking this morning (after the 3 hours had passed from my test snipe) it now shows "Failed!" for that item.  It still seems like time is the problem.  

I wonder why when I told Windows an incorrect time, temporarily setting my computer to Pacific time zone that SGW site uses, that didn't fix the issue and allow the bid to go through the the "correct" time.  

I don't think setting the bid too low could ever cause an issue.  What if a person sets it high, then leaves the house so he can't make any changes to the snipe amount set, and the auction has already gone above that snipe amount?  The snipe would not still just sit there as "Waiting...", right?   That is why I was expecting this all would run "in the cloud", and not in the system tray on the user's actual computer.  If a power failure happens during an important auction, that user is out of luck and no snipe would be sent.  

I don't have a firewall set on purpose on my end, but I have the kinda junky AT&T internet service.  Wonder if they're running something on their end without allowing me to opt in our out.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Brian,

Oh so it's definitely not the firewall, can you please elaborate why you think it's a time issue even though you said the datetime of the auction end date displays correctly? I believe we are very close to finding the issue and possibly a fix today...

**Comment by brianm80** [comment]
A lot of it my going by what you were convinced it was, with it being a time issue. 

But also, when I set the snipe at night it showed "Waiting...", even after the auction ended. 

The next morning it showed "Failed", which tells me the 3 hours passing (the difference in time zone from Eastern, my zone, and Pacific, the goodwill site's zone) might have changed that status of Waiting to read Failed.  I may have to test this theory on another auction and be sure I'm present at my computer exactly 3 hours after the auction's end time and see if the status updates right at that time.  

It's weird that manually changing the time on my Windows clock didn't make a difference though. Perhaps changing that only affects what is displayed in the system tray for me, but the computer itself knows that what I set wasn't actually true, and the computer's clock is what counts in this case for when it sends the snipe....not my fake Pacific time zone that I was seeing.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Brian,

Ok, thank you for your patience, as promised we found and fixed the issues you reported, we are glad to report to you that we have released a new update that fixes all the issues you were experiencing, this new version 24.08.27.1807 should now work perfect for you, as usual to update to the latest version, simply run the command on our homepage on Snipeable.com again in your powershell and it will update your installation to the latest version of Bid Sniper but please ensure the app is not already running when you do the installation by doing a simple fresh reboot before you install the new version, after successfully installing the new version then proceed to the file menu inside the app and click on the about menu item to confirm you are indeed using the latest version 24.08.27.1807 and if it matches then you should be perfect now!

It turns out the issues were all related to timezone discrepancies so as a result we are now using the timezone from sgw site even though you are in a different timezone, it will still show all the date times in sgw timezone so there is no discrepancies...

Please let us know if you have any further issues.

Best regards,
Snipeable.com
Technical Support

**Comment by brianm80** [comment]
OK, I did the update again today and this is the closest we ever got so far!  

I tried out a few snipes tonight and all of them actually made the sniper shot sound, which is the first time I've ever heard that.  
And they show "Sniped!" in green text right after the sound happens.  

The issue is that even though my bid amounts set to snipe were higher than the winning bidder's, I still didn't win any of them.  And in the bid history my bids never showed as happening.  This tells me they are being sent too late, after the auction actually ends.  Perhaps only by 1 or 2 seconds, but enough to lose and not even send in time for the auction ending.  Bummer.   I didn't have any high traffic things running on my internet connection, so that wouldn't be it.  My upload speed is usually pretty slow, so I thought of that ahead of time and made sure no photos or videos or whatever were uploading elsewhere in the house...or even downloading. 

We're definitely onto something here though, with the changing of the time zone to Pacific in the code to match the SGW site. 

I think something needs to change in the countdown timer to a second or two earlier for sending the snipe.  

Is the default advanced time different for every user?  You said above it takes into account the speed and strain of the internet connection.  Somehow that calculation hasn't been working just yet for my specific situation.  

Thanks for the fix so far.  We're so close!!

**Comment by shopgoodwill-auction-sniper** [comment]
Correction, the latest version is now 24.08.27.2112 we had to re-compile it one more time as there was some issues with files.

**Comment by shopgoodwill-auction-sniper** [comment]
Ok we will increase the timer a little bit tomorrow and see if that solves the issue or we may add a new file menu option that allows the user to increase the timer... but in the meanwhile can you try placing a bid manually on the sgw site to ensure there site is not preventing your bid too?

**Comment by shopgoodwill-auction-sniper** [comment]
also can you please confirm the snipes at least fired at the right time?

**Comment by brianm80** [comment]
OK, I'll do another test manual bid.  Do you mean doing one low on purpose (not planning to win) or actually trying to win something I might not even expect to win?  I did one manually to actually try to win yesterday and I was not prevented from bidding, I just lost fair and square.  I don't think there is any issue with the site or doing things normally directly on the SGW site.  Just issues with the snipe software.  

Yes, snipe sounds fired right around the time my clock changed minutes in the system tray.  The loading of the sound, and the length of the sound itself, make it hard to determine if it was starting to cue up right before that minute changeover or not.  If I can try another one I'll try to really watch when that sound happens.   The green text "Sniped!" didn't change over immediately from "Waiting...".  I think those took about 6 or 7 seconds from the change of the minute in my system tray.  

I show version 1807 in "about" in the menu, not the 2112 you mention above.  I'll delete again and hope I then have version 2112.   Are those compile time minutes/seconds in 24hr time format?

**Comment by shopgoodwill-auction-sniper** [comment]
No there is no need to do all that we will increase the timer tomorrow!

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Brian,

Ok we have released a new update version 24.08.28.1318 which includes some fine tuning adjustments, please try this version and see if it works for you, if it doesn't then we will increase the time a little more, the problem is we can't increase the timer too much because then it leaves too much room for another person to outbid you and we can't bring it too low either because then it will miss the bid so it's one of those things where we have to balance and fine tune to work perfect...

Please let me know how it goes...

Best Regards,
Snipeable.com
Technical Support

**Comment by brianm80** [comment]
OK.  I will try this.  Thanks for the update (again!)

**Comment by shopgoodwill-auction-sniper** [comment]
You're welcome! Hopefully you will have success with this one, but if you don't let us know and we will fine tune it until it does.

**Comment by brianm80** [comment]
OK, just tried one.  The snipe worked again, as it did in my tests last night.  And it still seemed to have been sent late.  The complete bid history does not show me or my snipe bid amount having taken place.  It's as if I was not bidding at all.  

I heard the snipe sound about 3 or 4 seconds after what I think was exactly the 0 seconds remaining time.  I had multiple windows up, including window's time with the seconds clock showing.  Those seconds matched the remaining time (in reverse) on the auction.  The issue with the SGW site is that you have to keep hitting refresh to see the zero on the clock, and don't really get to see the exact moment it hits zero unless you happen to click refresh right then. 

So we're still right about where we were last night.  Maybe the difference in seconds is getting closer.  Like you said above, there could be a danger that someone else could snipe at the last second if we send our too soon through the Bid Sniper software.   But that would be better than never even getting to bid.  I have lost like 25 great items so far in all of this experimenting!  But it's all learning for the future.  I would have won them if my snipes went through at slightly higher than the winner that is shown in the history.  

We're getting close!!!

**Comment by shopgoodwill-auction-sniper** [comment]
Ok, Thanks for letting us know Brian, and thank you for your patience and helpful information through this, what we are going to do at this point is refactor the sniping logic to use a different method to do the snipe that will eliminate the chances of it missing but this new logic refactoring could take us up to a week because as you can imagine it is a very hard and complex logic code, precision timing within 1-2 second frame is very hard to accomplish as you said if the snipe is sent too soon then the sniper can be outbid and if it is sent even 1 second too late then it misses the auction, but rest assured we will figure this out and get back to you with a final fix soon, we will keep you up-to-date here when we have the new version...

Best regards,
Snipeable.com
Technical Support

**Comment by brianm80** [comment]
OK, thanks for the update.  I imagine this stuff is pretty complicated to code.  I know nothing about that stuff! 

I'll keep watching for updates, or I'll get one in my email inbox when you next reply here after the next new logic update.  

In the meantime I'll bid the old fashioned way if I see something I want over the next week or so!

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Brian,

We have released the new version 24.08.30.1719 of the ShopGoodwill Sniper which resolves the issue you sent to us, you can download the new version by visiting our homepage at Snipeable.com and following the installation/update instructions on there.

Please let us know if we can be of further assistance.

Best regards,
Customer Service
Snipeable.com

**Comment by brianm80** [comment]
Great to hear.  I will give this a try soon and report back how the functionality works.  Looking forward to it.  No listings are ending soon that I am interested in tonight, so I can't really find anything to try this out with.  I'll find something on Saturday.

**Comment by brianm80** [comment]
It worked!  I was able to snipe and win 2 auctions tonight.  I wasn't even home at the time, so that's another nice benefit of this system working in the background while we don't even have to think about it.  I think everything is looking good.  I'm trying to think of any scenarios where it wouldn't be working for me.  I guess the only time would be if the auction has already climbed in price above what my snipe was set at, but that wouldn't be a problem with this software.  So far so good.  I think we got it.  

Thanks again for the 1.5 weeks of work on this thing!  I'm hoping I wasn't the only one having the issues, and this solved for your whole customer base where some of us may have had issues.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Brian,

Thank you for keeping us notified of your experience! We are excited to announce to you that we have added your new feature request called the "Auto Max Bid" feature that will basically win every auction for you by automatically bidding greater than the current maximum bid at the last second of the auction ensuring you win every auction! Now you no longer need to define your maximum bid before adding your snipe, you can simply leave the maximum bid field empty and it will automatically determine the maximum bid for you based on what the current maximum bid is at the last second of the auction ensuring you win every auction!

You can install/update the new version 24.09.04.1440 from our homepage as usual by following the install/update instructions on our homepage at Snipeable.com 

Please let us know if you have any further requests...

Best regards,
Customer Service
Snipeable.com

**Comment by brianm80** [comment]
Great, good to hear!  

Another feature of interest would be to allow for tweaking of the delay time before sending the snipe.  

Interestingly, after I wrote that comment above, I lost 2 auctions tonight due to the snipes not going through in time.  I had 3 set to snipe tonight and only one went through (not high enough, so I didn't win).  I looked at the bid history for that one and I see that my snipe went through at the 59 seconds mark before the next minute time when the auction ended.  I assume you have it set for a big longer delay (or AHEAD) before the auction end than that.  The other two snipes I set up today showed "Failed" and didn't show up in the bid history on the SGW site.  I thought everything was good, but I think that the sending of the snipe is just too last minute to go through safely.  

What is it set at in the software?  (we can't see or change that).  3 seconds?  That's typically what the Ebay auction softwares like EZ Sniper sets it at, and of course, that's in the cloud on their server, not running on our own machines in the system tray. 

I have a theory....I noticed that my task manager was showing a super used up RAM and CPU tonight when I came to my computer to check these results.  I had a couple things running in the background.  I'm thinking that my computer was simply that slow, enough to cause a delay in sending the snipe.  If the computer takes time to process the command to send the snipe in some cases it's too long and the auction ended.  Interesting that my first snipe went through this evening with 1 second to spare, and the other two did not.  I'm thinking that over the course of the evening while I wasn't home monitoring the computer, a sort of "memory leak" happened as too much stuff was running, and by the time of the 2nd and 3rd auctions ending, my RAM was almost blasted to full usage and the computer just couldn't keep up with what it needed to in order to send the snipe with 1 or whatever seconds you have it set at.  

So.....I'm thinking those with older computers, or slower computers, need to have the snipe setting at 3 or 4 seconds ahead of auction end time, in order to compensate and maybe send the snipe in at 1 or 2 seconds.  

Think this is what's happening?   It's the only explanation I have for this thing working for me a couple days ago and suddenly failing again.

**Comment by shopgoodwill-auction-sniper** [comment]
Hi Brian,

We have fixed the issue you are experiencing in the latest version, please update to the newest version because that has more than just a new feature it also fixes numerous bugs and issues with sniping as well. We have intentionally not put a setting for the timer because the software itself should be smart enough to figure that out, and in fact we even took out the stale expiration timer as well from the menu as you might notice in the new version because it should be smart enough to figure all that out too, what's the point of using an app if you have to tell it how to do what it is designed to do? Therefore, we believe in setting-less apps here because the worst thing that a user can experience is being overwhelmed by a bunch of technical settings that they have no idea what it means, so we try to figure out all the settings for the user so they have a simple interface that easy to use and intuitive. The timer itself is set to snipe at the very last second of the auction, there would be no point in using a sniper software if it's anything greater than the last second because that would defeat the purpose of what it is designed for. Furthermore, I believe you will be glad once you see the newest version as it solves a lot of issues including refining the sniping logic even more than we already have done in the last version you had success with, so basically the new version got even better! Which is how we believe it should be... anyhow please give the latest version a try let us know what your thoughts are, we believe you will be satisfied with it as it solves a lot of bugs that you didn't even report we throughly tested and found all the bugs ourself in this last week that you hadn't heard from us, because we have been throughly testing and refining the sniper logic since the last update for over a week now, so there are quite a bit of improvements which I believe you will notice as you are using it, you will notice a lot of the old issues you used to have are not there anymore because we found every issue and fixed it to perfection, but we will let you to be the judge of that, not to mention now you don't have to determine the maximum bid anymore which makes it so much easier to just win every auction basically, the new version pretty much guarantees you win every auction now effortlessly! Anyhow, we will let you be the judge of that...

Happy bidding! Enjoy.

Best regards,
Technical Support
Snipeable.com
